version: '3.8'

services:
  # 主节点
  mongo0:
    image: mongo-replica-set
    restart: always
    privileged: true
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    command: --replSet replica-set --keyFile /root/mongod/mongo.key
  # 副节点
  mongo1:
    image: mongo-replica-set
    restart: always
    privileged: true
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    command: --replSet replica-set --keyFile /root/mongod/mongo.key
  # 仲裁节点
  mongo2:
    image: mongo-replica-set
    restart: always
    privileged: true
    ports:
      - 27019:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    command: --replSet replica-set --keyFile /root/mongod/mongo.key

networks:
  # 默认使用自己创建的网络
  default:
    external:
      name: local-net
