FROM mongo:4.0.28

LABEL maintainer="leimeng"
#将秘钥文件复制到镜像中
COPY auth.key /app/auth.key
COPY wait-for-it.sh /app/wait-for-it.sh
RUN chown -R mongodb:mongodb /app/auth.key
#设置秘钥文件权限，这一步非常关键
RUN chmod 600 /app/auth.key
#设置可执行文件权限
RUN chmod a+x /app/wait-for-it.sh